spring.application.name=ShelfSync

spring.datasource.url=jdbc:mysql://localhost:3306/ShelfSync
spring.datasource.username=root
spring.datasource.password=Shubham13
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=d5826ea2fbf9226afe71c261b6d2fa607da82a59ddefab09e3a8af6bf96a7f0f
jwt.expiration=604800000

app.admin.email=admin123@gmail.com
app.admin.password=12345678
app.admin.Phone=7020089177